export const INCREASE_COUNT = "INCREASE_COUNT";
export const GET_RANDOM_NUMBER = "GET_RANDOM_NUMBER";
export const RECIEVED_RANDOM_NUMBER = "RECIEVED_RANDOM_NUMBER";
export const GET_RANDOM_NUMBER_ERROR = "GET_RANDOM_NUMBER_ERROR";